[build]
command = "npm install && npm run build:netlify"
publish = ".output/netlify"

[functions]
directory = ".output/netlify/server"

[[redirects]]
from = "/*"
to = "/.netlify/functions/main"
status = 200
force = true