[build]
command = "npm ci && npm run build:netlify"
publish = ".output/netlify"

[functions]
directory = ".output/netlify/server"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200